// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_hLnjrzQCJ2MlIj7EE3IHQtkcgbgBX4g',
    appId: '1:283394285640:web:61005a2d25585a4932387d',
    messagingSenderId: '283394285640',
    projectId: 'mdp-gold-9398b',
    authDomain: 'mdp-gold-9398b.firebaseapp.com',
    databaseURL: 'https://mdp-gold-9398b-default-rtdb.firebaseio.com',
    storageBucket: 'mdp-gold-9398b.firebasestorage.app',
    measurementId: 'G-6NGZSR694D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5hAvcM3Wu8qVT_d5zBk7Y2U0f3bCkVAo',
    appId: '1:283394285640:android:e02244b198aaccb932387d',
    messagingSenderId: '283394285640',
    projectId: 'mdp-gold-9398b',
    databaseURL: 'https://mdp-gold-9398b-default-rtdb.firebaseio.com',
    storageBucket: 'mdp-gold-9398b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHeSv8uSSi7j6_UCHjdFu9fgE6J-qcB_o',
    appId: '1:283394285640:ios:e470ac179ca9c62f32387d',
    messagingSenderId: '283394285640',
    projectId: 'mdp-gold-9398b',
    databaseURL: 'https://mdp-gold-9398b-default-rtdb.firebaseio.com',
    storageBucket: 'mdp-gold-9398b.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHeSv8uSSi7j6_UCHjdFu9fgE6J-qcB_o',
    appId: '1:283394285640:ios:e470ac179ca9c62f32387d',
    messagingSenderId: '283394285640',
    projectId: 'mdp-gold-9398b',
    databaseURL: 'https://mdp-gold-9398b-default-rtdb.firebaseio.com',
    storageBucket: 'mdp-gold-9398b.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_hLnjrzQCJ2MlIj7EE3IHQtkcgbgBX4g',
    appId: '1:283394285640:web:c3db6c3acc3c3eac32387d',
    messagingSenderId: '283394285640',
    projectId: 'mdp-gold-9398b',
    authDomain: 'mdp-gold-9398b.firebaseapp.com',
    databaseURL: 'https://mdp-gold-9398b-default-rtdb.firebaseio.com',
    storageBucket: 'mdp-gold-9398b.firebasestorage.app',
    measurementId: 'G-BWEXPGCLNG',
  );
}
